plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/lao/.openclaw/workspace/projects/decana-repo/landings/mortgage brokers"
publishOrigin = "default"
base = "/home/lao/.openclaw/workspace/projects/decana-repo/landings/mortgage brokers"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]